language: python
dist: xenial
sudo: required
python:
 - "3.7"
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['bash', 'coreutils']
cache:
  directories:
    - /home/travis/.cache/pip
before_install:
  - pip install poetry
install:
  - poetry install
jobs:
  include:
    - stage: Build
      script:
        - poetry build
    - stage: Unit Tests
      script:
        - poetry run tox
    - stage: Install
      script:
        - which cloud-secrets
        - python -c 'from cloudsecrets.gcp import Secrets'
